bau: Improve the descriptions of the tests
This changes the output from:

```
Running test : example-match.json
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : example-no-match.json
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runForSimpleCase()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runForExtensiveCase()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runForWhenAllElementsAreVerifiedAndNoMultipleValues()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runForExtensiveCase()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runCase()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : runForUserAccountCreation()
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
```

To:

```
Running test : example-match.json
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : example-no-match.json
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Simple request with level of assurance 1
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Complex request with level of assurance 1
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Simple request with level of assurance 2
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Complex request with level of assurance 2
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Simple request with address missing optional fields
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Running test : Simple user account creation request
(remove accountCreationUrl from verify-matching-service-test-tool.yml to skip this if you don't need to test account creation)
Status : FAILED
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)

Test execution finished. Number of all tests: 8
```

Authors: @richardtowers